/**
 * models/User.js
 * ------------------------------------------------------------------
 * Data access for the `auth_users` table (equivalent of a Mongoose model).
 *
 * Columns:
 *   id           uuid  - primary key, generated by Postgres (gen_random_uuid())
 *   name         text  - full name
 *   mobile       text  - 10 digit Indian mobile, UNIQUE
 *   email        text  - UNIQUE
 *   passwordHash text  - bcrypt hash, NEVER the raw password
 *   createdAt    tstz  - signup time
 *   lastLogin    tstz  - most recent successful login
 *
 * Every function here returns a plain object or null and throws a readable
 * DatabaseError for anything that is not a simple "not found" case, so callers
 * stay simple and the user gets an actionable message.
 */

"use strict";

const { requireDb, toDatabaseError, TABLES } = require("../config/db");

/** The exact columns safe to send to the browser (passwordHash excluded). */
const PUBLIC_COLUMNS = "id, name, mobile, email, createdAt, lastLogin";

/**
 * Creates a new account.
 * @param {{name:string, mobile:string, email:string, passwordHash:string}} data
 * @returns {Promise<{ok:true,user:object} | {ok:false,code:string,message:string}>}
 */
async function createUser({ name, mobile, email, passwordHash }) {
  const db = requireDb();

  const { data, error } = await db
    .from(TABLES.users)
    .insert({
      name,
      mobile,
      email,
      passwordHash,
      createdAt: new Date().toISOString(),
      lastLogin: new Date().toISOString(),
    })
    .select(PUBLIC_COLUMNS)
    .single();

  if (error) {
    // Postgres unique violation -> the caller already did a friendly pre-check,
    // so hitting this means a race. Still return a clean message.
    if (error.code === "23505") {
      return { ok: false, code: "DUPLICATE", message: "Mobile number or email already registered." };
    }
    // Anything else is a real database problem and should surface as such.
    throw toDatabaseError(error);
  }

  return { ok: true, user: data };
}

/** Finds one account by email. Returns null when not found. */
async function findByEmail(email) {
  const db = requireDb();

  const { data, error } = await db
    .from(TABLES.users)
    .select("id, name, mobile, email, passwordHash, createdAt, lastLogin")
    .eq("email", email)
    .maybeSingle();

  if (error) throw toDatabaseError(error);
  return data;
}

/** Finds one account by mobile number. Returns null when not found. */
async function findByMobile(mobile) {
  const db = requireDb();

  const { data, error } = await db
    .from(TABLES.users)
    .select("id, name, mobile, email, passwordHash, createdAt, lastLogin")
    .eq("mobile", mobile)
    .maybeSingle();

  if (error) throw toDatabaseError(error);
  return data;
}

/**
 * Login accepts either a mobile number or an email, so we try both.
 * @param {string} identifier - 10 digit mobile OR email address
 */
async function findByIdentifier(identifier) {
  // A 10 digit string can only be a mobile number; anything with @ is an email.
  // Trying both would be a wasted round trip and an unnecessary info leak.
  if (/^\d{10}$/.test(identifier)) return findByMobile(identifier);
  return findByEmail(identifier);
}

/** Finds one account by id. Returns null when not found. */
async function findById(id) {
  const db = requireDb();

  const { data, error } = await db
    .from(TABLES.users)
    .select(PUBLIC_COLUMNS)
    .eq("id", id)
    .maybeSingle();

  if (error) throw toDatabaseError(error);
  return data;
}

/** Cheap existence check used to give friendly "already registered" messages. */
async function isEmailTaken(email) {
  const db = requireDb();

  const { count, error } = await db
    .from(TABLES.users)
    .select("id", { count: "exact", head: true })
    .eq("email", email);

  if (error) throw toDatabaseError(error);
  return (count ?? 0) > 0;
}

/** Same as isEmailTaken but for mobile numbers. */
async function isMobileTaken(mobile) {
  const db = requireDb();

  const { count, error } = await db
    .from(TABLES.users)
    .select("id", { count: "exact", head: true })
    .eq("mobile", mobile);

  if (error) throw toDatabaseError(error);
  return (count ?? 0) > 0;
}

/**
 * Records a successful login time.
 *
 * Deliberately swallows its own errors: the user is already authenticated at
 * this point, so a failure to write a timestamp must never deny them a login.
 */
async function updateLastLogin(id) {
  try {
    const db = requireDb();
    await db
      .from(TABLES.users)
      .update({ lastLogin: new Date().toISOString() })
      .eq("id", id);
  } catch (err) {
    console.warn("[warn] could not update lastLogin:", err.message);
  }
}

module.exports = {
  createUser,
  findByEmail,
  findByMobile,
  findByIdentifier,
  findById,
  isEmailTaken,
  isMobileTaken,
  updateLastLogin,
  PUBLIC_COLUMNS,
};
